export const categories = [
  "Tech",
  "Food",
  "Music",
  "Sports",
  "Education",
  "Art & Culture",
  "Health & Wellness",
  "Business & Networking",
  "Lifestyle",
  "Charity & Fundraising",
  "Travel & Adventure",
  "Gaming",
  "Film & Media",
]
